[tox]
envlist = py311, unit, functional
isolated_build = True
requires = tox-uv

[testenv]
commands_pre =
    uv pip install -e ".[dev]"
commands =
    pytest -s --tb=short --cache-clear

[testenv:unit]
commands =
    pytest -s -m unit --tb=short --cache-clear

[testenv:functional]
commands =
    pytest -s -m functional --tb=short --cache-clear
