[tox]
envlist = unit, functional
isolated_build = True
requires = tox-uv
recreate = False

[testenv]
allowlist_externals = pytest
setenv =
    PYTHONPATH = {toxinidir}
commands_pre =
    uv sync --extra dev
commands =
    pytest -s --tb=short --cache-clear

[testenv:unit]
commands =
    pytest -s -m unit --tb=short --cache-clear

[testenv:functional]
commands =
    pytest -s -m functional --tb=short --cache-clear
