services:
  nexus:
    image: sonatype/nexus3:3.78.2
    container_name: nexus
    restart: always
    ports:
      - "17000:8081"   # Nexus itself
      - "17001:17001"  # docker registry for http anonymous docker registry
      - "17003:17003"  # docker registry for http non-anonymous docker registry
    volumes:
      - nexus-data:/nexus-data
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms1g -Xmx1g"

  nginx:
    image: nginx:1.27.4
    container_name: nginx-nexus
    restart: always
    depends_on:
      - nexus
    ports:
      - "17002:17002"  # docker registry for https anonymous docker registry
      - "17004:17004"  # docker registry for https non-anonymous docker registry
    volumes:
      - nginx-data:/etc/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./scripts/nexus/generate-certs.sh:/etc/nginx/ssl/generate-certs.sh
    entrypoint: [ "/bin/sh", "-c", "/etc/nginx/ssl/generate-certs.sh && exec nginx -g 'daemon off;'" ]

#  localstack:
#    image: localstack/localstack-pro
##    image: localstack/localstack
#    container_name: localstack
#    restart: always
#    ports:
#      - "4566:4566"            # LocalStack Gateway
#      - "4510-4559:4510-4559"  # external services port range
##      - "18000:8081"   # LocalStack itself
##      - "18000:4566"   # LocalStack Gateway
##      - "18002-18003:18002-18003"  # docker registry for http/https anonymous docker registry
##      - "18004-18005:18004-18005"  # docker registry for http/https non-anonymous docker registry
#    environment:
#      SERVICES: "ecr,s3"
#      AWS_ACCESS_KEY_ID: "test"
#      AWS_SECRET_ACCESS_KEY: "test"
#      AWS_DEFAULT_REGION: "us-east-1"
#    volumes:
#      - localstack-data:/var/lib/localstack
##      - /var/run/docker.sock:/var/run/docker.sock
#    extra_hosts:
#      - "localstack.localhost:127.0.0.1"

networks:
  default:
    name: devbox-net

volumes:
  nexus-data:
  nginx-data:
#  localstack-data: