name: Lint and Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false 
      - name: Set up Python
        uses: actions/setup-python@v5 # zizmor: ignore[unpinned-uses]
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install poetry && poetry install --with dev

      - name: Run linters
        run: poetry run ruff check .

  tests:
   strategy:
     max-parallel: 2
     fail-fast: false
     matrix:
       os:
         - ubuntu-22.04
       python-version:
         - '3.10'
         - '3.11'
         - '3.12'
         - '3.13'
   runs-on: ${{ matrix.os }}
   permissions:
     contents: read
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4  # zizmor: ignore[unpinned-uses]
       with:
          fetch-depth: 0
          lfs: true
          persist-credentials: false
     - name: Set up Python
       uses: actions/setup-python@v5  # zizmor: ignore[unpinned-uses]
       with:
         python-version: ${{ matrix.python-version }}

     - name: Install dependencies
       run: pip install poetry tox && poetry install --with dev

     - name: Run tests
       run: |
        tox -e unit
        tox -e functional
